export const otherIcons: any = {
  Admin: "user-tie",
  Ghost: "ghost",
  Living: "heart",
  Unknown: "question",
  "Ancient Crew": "hands-holding-circle",
  "Ash Walker": "dragon",
  Hermit: "volcano",
  "Beach Bum": "beer-mug-empty",
  Lifebringer: "hand-holding-heart",
  "Space Bartender": "beer-mug-empty",
  "Cyber Police": "handcuffs",
  Glitch: "bug",
  "Lavaland Syndicate": "section",
  "Space Syndicate": "section",
  "Cybersun Space Syndicate": "section",
  "Cybersun Space Syndicate Captain": "text",
  "Derelict Drone": "robot",
  "Maintenance Drone": "robot",
  "Free Golem": "chess-rook",
  "Servant Golem": "chess-rook",
  "Venus Human Trap": "plant-wilt",
  "Ghost Role": "ghost",
  "Big Brother": "eye",
  "Bridge Assistant": "shield-heart",
  "Cargo Gorilla": "box",
  Cargorilla: "box",
  "Veteran Security Advisor": "person-cane",
  "Avatar of the Wish Granter": "wand-magic-sparkles",
  "revolution enemy": "hand-back-fist",
  "exiled headrev": "hand-back-fist",
  Santa: "sleigh",
  valentine: "heart",
  survivalist: "x",
  highlander: "face-angry",
  "ERT Generic": "x",
  Skeleton: "skull",
  "Unassigned Crewmember": "id-card",
  Blueshield: "shield",
  Synthetic: "handshake-angle",
  Virologist: "virus",
};
