export const otherIcons: any = {
  Admin: "",
  Ghost: "",
  Living: "",
  Unknown: "",
  "Ancient Crew": "",
  "Ash Walker": "",
  Hermit: "",
  "Beach Bum": "",
  Lifebringer: "",
  "Space Bartender": "",
  "Cyber Police": "",
  Glitch: "",
  "Lavaland Syndicate": "",
  "Space Syndicate": "",
  "Cybersun Space Syndicate": "",
  "Cybersun Space Syndicate Captain": "",
  "Derelict Drone": "",
  "Maintenance Drone": "",
  "Free Golem": "",
  "Servant Golem": "",
  "Venus Human Trap": "",
  "Ghost Role": "",
  "Big Brother": "",
  "Bridge Assistant": "",
  "Cargo Gorilla": "",
  Cargorilla: "",
  "Veteran Security Advisor": "",
  "Avatar of the Wish Granter": "",
  "revolution enemy": "",
  "exiled headrev": "",
  Santa: "",
  valentine: "",
  survivalist: "",
  highlander: "",
  "ERT Generic": "",
  Skeleton: "",
  "Unassigned Crewmember": "",
  Blueshield: "",
  Synthetic: "",
  Virologist: "",
};
