export const antagIcons: any = {
  Traitor: "",
  "Blood Brother": "",
  Spy: "",
  "Malf AI": "",
  "Head Revolutionary": "",
  Revolutionary: "",
  Provocateur: "",
  "Nuclear Operative": "",
  "Clown Operative": "",
  "Operative (Midround)": "",
  "Lone Operative": "",
  "Contractor Support Unit": "",
  "Operative Overwatch Agent": "",
  "Syndicate Assault Cyborg": "",
  "Syndicate Cyborg": "",
  "Syndicate Infiltrator": "",
  "Syndicate Medical Cyborg": "",
  "Syndicate Monkey Agent": "",
  "Syndicate Sabotage Cyborg": "",
  "Battlecruiser Captain": "",
  "Battlecruiser Crew": "",
  Abductor: "",
  "Abductor Agent": "",
  "Abductor Scientist": "",
  "Abductor Solo": "",
  "  Blob Infection": "",
  "Sentient Disease": "",
  Morph: "",
  Heretic: "",
  "Heretic Smuggler": "",
  Changeling: "",
  "Changeling (Midround)": "",
  "Stowaway Changeling": "",
  Cultist: "",
  Nightmare: "",
  "Space Dragon": "",
  "Space Ninja": "",
  Spider: "",
  Xenomorph: "",
  "Space Pirate": "",
  Revenant: "",
  "Paradox Clone": "",
  Fugitive: "",
  "Fugitive Hunter": "",
  "Pyroclastic Anomaly Slime": "",
  Wizard: "",
  "Wizard (Midround)": "",
  Apprentice: "",
  "Slaughter Demon": "",
};
