export const antagIcons: any = {
  Traitor: "jedi",
  "Blood Brother": "user-group",
  Spy: "user-secret",
  "Malf AI": "eye-slash",
  "Head Revolutionary": "hand-back-fist",
  Revolutionary: "hand-back-fist",
  Provocateur: "hand-back-fist",
  "Nuclear Operative": "users",
  "Clown Operative": "face-grin-tears",
  "Operative (Midround)": "users",
  "Lone Operative": "circle-radiation",
  "Contractor Support Unit": "x",
  "Operative Overwatch Agent": "jedi",
  "Syndicate Assault Cyborg": "jedi",
  "Syndicate Cyborg": "jedi",
  "Syndicate Infiltrator": "jedi",
  "Syndicate Medical Cyborg": "jedi",
  "Syndicate Monkey Agent": "jedi",
  "Syndicate Sabotage Cyborg": "jedi",
  "Battlecruiser Captain": "rocket",
  "Battlecruiser Crew": "rocket",
  Abductor: "shuttle-space",
  "Abductor Agent": "shuttle-space",
  "Abductor Scientist": "shuttle-space",
  "Abductor Solo": "shuttle-space",
  "Blob Infection": "virus-covid",
  "Sentient Disease": "brain",
  Morph: "certificate",
  Heretic: "hamsa",
  "Heretic Smuggler": "hamsa",
  Changeling: "people-arrows",
  "Changeling (Midround)": "people-arrows",
  "Stowaway Changeling": "people-arrows",
  Cultist: "hands-holding-circle",
  Nightmare: "lightbulb",
  "Space Dragon": "dragon",
  "Space Ninja": "hurricane",
  Spider: "spider",
  Xenomorph: "locust",
  "Space Pirate": "skull-crossbones",
  Revenant: "ghost",
  "Paradox Clone": "shuffle",
  Fugitive: "person-running",
  "Fugitive Hunter": "person-running",
  "Pyroclastic Anomaly Slime": "water",
  Wizard: "hat-wizard",
  "Wizard (Midround)": "hat-wizard",
  Apprentice: "toolbox",
  "Slaughter Demon": "otter",
};
