export const iconMap: any = {
  AI: "eye",
  Assistant: "toolbox",
  "Atmospheric Technician": "fan",
  Bartender: "cocktail",
  "Bit Avatar": "code",
  Bitrunner: "gamepad",
  Botanist: "seedling",
  "Brig Physician": "shield-heart",
  Captain: "crown",
  "Cargo Gorilla": "paw",
  "Cargo Technician": "box",
  "CentCom Commander": "star",
  "CentCom Head Intern": "pen-fancy",
  "CentCom Intern": "pen-alt",
  "CentCom Official": "medal",
  Chaplain: "cross",
  Chef: "utensils",
  Chemist: "prescription-bottle",
  "Chief Engineer": "user-astronaut",
  "Chief Medical Officer": "user-md",
  Clown: "face-grin-tears",
  Cook: "utensils",
  Coroner: "skull",
  Curator: "book",
  "Cyber Police": "qrcode",
  Cyborg: "robot",
  Detective: "user-secret",
  Geneticist: "dna",
  "Head of Personnel": "dog",
  "Head of Security": "user-shield",
  "Big Brother": "eye",
  Janitor: "soap",
  Lawyer: "gavel",
  "Medical Doctor": "staff-snake",
  "Nt Secretary": "clipboard-check",
  Animal: "paw",
  Mime: "comment-slash",
  Paramedic: "truck-medical",
  "Personal AI": "mobile-alt",
  Prisoner: "lock",
  Psychologist: "brain",
  Quartermaster: "sack-dollar",
  "Research Director": "user-graduate",
  Roboticist: "battery-half",
  Scientist: "flask",
  "Security Officer (Cargo)": "shield-halved",
  "Security Officer (Engineering)": "shield-halved",
  "Security Officer (Medical)": "shield-halved",
  "Security Officer (Science)": "shield-halved",
  "Security Officer": "shield-halved",
  "Shaft Miner": "digging",
  "Station Engineer": "gears",
  Synthetic: "handshake-angle",
  "Syndicate Operative": "dragon",
  "Veteran Security Advisor": "ribbon",
  Warden: "handcuffs",
  Worker: "screwdriver-wrench",
  Traitor: "jedi",
  "Blood Brother": "user-group",
  Changeling: "people-arrows",
  "Clown Operative": "face-grin-tears",
  Cultist: "hands-holding-circle",
  Revolutionary: "hand-back-fist",
  Heretic: "hamsa",
  "Malfunctioning AI": "eye-slash",
  "Nuclear Operative": "users",
  Spy: "user-secret",
  Wizard: "hat-wizard",
  "Syndicate Sleeper Agent": "jedi",
  Abductor: "user-astronaut",
  Blob: "virus",
  "Blob Infection": "virus-covid",
  Fugitive: "person-running",
  Glitch: "bug",
  "Lone Operative": "circle-radiation",
  Nightmare: "lightbulb",
  "Nuclear Assailant": "users",
  Obsessed: "face-flushed",
  "Paradox Clone": "shuffle",
  Revenant: "ghost",
  "Sentient Creature": "brain",
  "Space Dragon": "dragon",
  "Space Ninja": "hurricane",
  "Value Drifted AI": "eye-slash",
  "Wizard (Midround)": "hat-wizard",
  Xenomorph: "otter",
  "Syndicate Infiltrator": "jedi",
  "Heretic Smuggler": "hamsa",
  Provocateur: "hand-back-fist",
  "Stowaway Changeling": "people-arrows",
};
