import { IconProp } from "@fortawesome/fontawesome-svg-core"; // Import IconProp type
interface IconProps {
	[key: string]: IconProp;
}

export const Icons: IconProps = {
	// Station Icons

	AI: "eye",
	Animal: "paw",
	Assistant: "toolbox",
	"Atmospheric Technician": "fan",
	Bartender: "cocktail",
	Bitrunner: "gamepad",
	Botanist: "seedling",
	"Brig Physician": "shield-heart",
	Captain: "crown",
	"Cargo Technician": "box",
	Chaplain: "cross",
	Chemist: "prescription-bottle",
	"Chief Engineer": "user-astronaut",
	"Chief Medical Officer": "user-md",
	Clown: "face-grin-tears",
	Cook: "utensils",
	Coroner: "skull",
	Curator: "book",
	Cyborg: "robot",
	Detective: "user-secret",
	Geneticist: "dna",
	"Head of Personnel": "dog",
	"Head of Security": "user-shield",
	Janitor: "soap",
	Lawyer: "gavel",
	"Medical Doctor": "staff-snake",
	Mime: "comment-slash",
	"Nt Secretary": "clipboard-check",
	Paramedic: "truck-medical",
	Prisoner: "lock",
	Psychologist: "brain",
	Quartermaster: "sack-dollar",
	"Research Director": "user-graduate",
	Roboticist: "battery-half",
	Scientist: "flask",
	"Security Officer": "shield-halved",
	"Shaft Miner": "digging",
	"Station Engineer": "gears",
	Warden: "handcuffs",
	Worker: "screwdriver-wrench",

	// Antag Icons

	Traitor: "jedi",
	"Blood Brother": "user-group",
	Spy: "user-secret",
	"Malf AI": "eye-slash",
	"Head Revolutionary": "hand-back-fist",
	Revolutionary: "hand-back-fist",
	Provocateur: "hand-back-fist",
	"Nuclear Operative": "users",
	"Clown Operative": "face-grin-tears",
	"Operative (Midround)": "users",
	"Lone Operative": "circle-radiation",
	"Contractor Support Unit": "x",
	"Operative Overwatch Agent": "jedi",
	"Syndicate Assault Cyborg": "jedi",
	"Syndicate Cyborg": "jedi",
	"Syndicate Infiltrator": "jedi",
	"Syndicate Medical Cyborg": "jedi",
	"Syndicate Monkey Agent": "jedi",
	"Syndicate Sabotage Cyborg": "jedi",
	"Battlecruiser Captain": "rocket",
	"Battlecruiser Crew": "rocket",
	Abductor: "shuttle-space",
	"Abductor Agent": "shuttle-space",
	"Abductor Scientist": "shuttle-space",
	"Abductor Solo": "shuttle-space",
	Blob: "virus-covid",
	"Blob Infection": "virus-covid",
	Morph: "certificate",
	Heretic: "hamsa",
	"Heretic Smuggler": "hamsa",
	Changeling: "people-arrows",
	"Changeling (Midround)": "people-arrows",
	"Stowaway Changeling": "people-arrows",
	Cultist: "hands-holding-circle",
	Nightmare: "lightbulb",
	"Space Dragon": "dragon",
	"Space Ninja": "hurricane",
	Spider: "spider",
	Xenomorph: "locust",
	"Space Pirate": "skull-crossbones",
	Revenant: "ghost",
	"Paradox Clone": "shuffle",
	Fugitive: "person-running",
	"Fugitive Hunter": "person-running",
	"Pyroclastic Anomaly Slime": "water",
	Wizard: "hat-wizard",
	"Wizard (Midround)": "hat-wizard",
	Apprentice: "toolbox",
	"Slaughter Demon": "otter",

	// Other Icons

	Admin: "user-tie",
	Ghost: "ghost",
	Living: "heart",
	Unknown: "question",
	"Ancient Crew": "hands-holding-circle",
	"Ash Walker": "dragon",
	Hermit: "volcano",
	"Beach Bum": "beer-mug-empty",
	Lifebringer: "hand-holding-heart",
	"Space Bartender": "beer-mug-empty",
	"Cyber Police": "handcuffs",
	Glitch: "bug",
	"Lavaland Syndicate": "section",
	"Space Syndicate": "section",
	"Cybersun Space Syndicate": "section",
	"Cybersun Space Syndicate Captain": "section",
	"Derelict Drone": "robot",
	"Maintenance Drone": "robot",
	"Free Golem": "chess-rook",
	"Servant Golem": "chess-rook",
	"Venus Human Trap": "plant-wilt",
	"Ghost Role": "ghost",
	"Big Brother": "eye",
	"Bridge Assistant": "shield-heart",
	"Cargo Gorilla": "box",
	Cargorilla: "box",
	"Veteran Security Advisor": "person-cane",
	"Avatar of the Wish Granter": "wand-magic-sparkles",
	"Revolution Enemy": "hand-back-fist",
	"Exiled Headrev": "hand-back-fist",
	Santa: "sleigh",
	Valentine: "heart",
	Survivalist: "x",
	Highlander: "face-angry",
	"ERT Generic": "x",
	Skeleton: "skull",
	"Unassigned Crewmember": "id-card",
	Blueshield: "shield",
	Synthetic: "handshake-angle",
	Virologist: "virus",
};

export const Joblist = {
	Station: {
		Komuta: [
			"Captain",
			"Head of Personnel",
			"Chief Engineer",
			"Quartermaster",
			"Chief Medical Officer",
			"Research Director",
			"Head of Security",
		],
		Güvenlik: [
			"Head of Security",
			"Warden",
			"Detective",
			"Brig Physician",
			"Security Officer",
		],
		Mühendislik: [
			"Chief Engineer",
			"Station Engineer",
			"Worker",
			"Atmospheric Technician",
		],
		Medikal: [
			"Chief Medical Officer",
			"Medical Doctor",
			"Paramedic",
			"Chemist",
			"Coroner",
		],
		Bilim: ["Research Director", "Scientist", "Roboticist", "Geneticist"],
		Kargo: ["Quartermaster", "Cargo Technician", "Shaft Miner", "Bitrunner"],
		Servis: [
			"Head of Personnel",
			"Nt Secretary",
			"Bartender",
			"Botanist",
			"Cook",
			"Janitor",
			"Clown",
			"Mime",
			"Curator",
			"Lawyer",
			"Chaplain",
			"Psychologist",
		],
		Silikon: ["AI", "Cyborg"],
		Bağımsız: ["Assistant", "Animal", "Prisoner"],
	},
	Antag: {
		Sendika: [
			"Traitor",
			"Blood Brother",
			"Spy",
			"Malf AI",
			"Head Revolutionary",
			"Revolutionary",
			"Provocateur",
			"Nuclear Operative",
			"Clown Operative",
			"Operative (Midround)",
			"Lone Operative",
			"Contractor Support Unit",
			"Operative Overwatch Agent",
			"Syndicate Assault Cyborg",
			"Syndicate Cyborg",
			"Syndicate Infiltrator",
			"Syndicate Medical Cyborg",
			"Syndicate Monkey Agent",
			"Syndicate Sabotage Cyborg",
			"Battlecruiser Captain",
			"Battlecruiser Crew",
		],
		"Uzaysal Tehdi̇tler": [
			"Nightmare",
			"Space Dragon",
			"Space Ninja",
			"Spider",
			"Xenomorph",
			"Space Pirate",
			"Revenant",
			"Paradox Clone",
			"Fugitive",
			"Fugitive Hunter",
			"Pyroclastic Anomaly Slime",
		],
		Kaçıranlar: [
			"Abductor",
			"Abductor Agent",
			"Abductor Scientist",
			"Abductor Solo",
		],
		"Biyolojik Tehlikeler": ["Blob", "Blob Infection", "Morph"],
		Sihir: [
			"Heretic",
			"Heretic Smuggler",
			"Changeling",
			"Changeling (Midround)",
			"Stowaway Changeling",
			"Cultist",
		],
		"Büyücü Federasyonu": [
			"Wizard",
			"Wizard (Midround)",
			"Apprentice",
			"Slaughter Demon",
		],
	},
	Other: {
		"Hayalet Rolleri": [
			"Ancient Crew",
			"Ash Walker",
			"Hermit",
			"Beach Bum",
			"Lifebringer",
			"Space Bartender",
			"Cyber Police",
			"Glitch",
			"Lavaland Syndicate",
			"Space Syndicate",
			"Cybersun Space Syndicate",
			"Cybersun Space Syndicate Captain",
			"Derelict Drone",
			"Maintenance Drone",
			"Free Golem",
			"Servant Golem",
			"Venus Human Trap",
			"Ghost Role",
		],
		Event: [
			"Big Brother",
			"Bridge Assistant",
			"Cargo Gorilla",
			"Cargorilla",
			"Veteran Security Advisor",
			"Avatar of the Wish Granter",
			"Revolution Enemy",
			"Exiled Headrev",
			"Santa",
			"Valentine",
			"Survivalist",
			"Highlander",
		],
		"Rol Dışı": ["Admin", "Ghost", "Living", "Unknown"],
		Diğer: ["ERT Generic", "Skeleton", "Unassigned Crewmember"],
		Kaldırılmış: ["Blueshield", "Synthetic", "Virologist"],
	},
};
