import { IconProp } from "@fortawesome/fontawesome-svg-core"; // Import IconProp type
interface IconProps {
	[key: string]: IconProp;
}

export const Icons: IconProps = {
	// Station Icons

	AI: "eye",
	Animal: "paw",
	Assistant: "toolbox",
	"Atmospheric Technician": "fan",
	Bartender: "cocktail",
	Bitrunner: "gamepad",
	Botanist: "seedling",
	"Brig Physician": "shield-heart",
	Captain: "crown",
	"Cargo Technician": "box",
	Chaplain: "cross",
	Chemist: "prescription-bottle",
	"Chief Engineer": "user-astronaut",
	"Chief Medical Officer": "user-md",
	Clown: "face-grin-tears",
	Cook: "utensils",
	Coroner: "skull",
	Curator: "book",
	Cyborg: "robot",
	Detective: "user-secret",
	Geneticist: "dna",
	"Head of Personnel": "dog",
	"Head of Security": "user-shield",
	Janitor: "soap",
	Lawyer: "gavel",
	"Medical Doctor": "staff-snake",
	Mime: "comment-slash",
	"Nt Secretary": "clipboard-check",
	Paramedic: "truck-medical",
	Prisoner: "lock",
	Psychologist: "brain",
	Quartermaster: "sack-dollar",
	"Research Director": "user-graduate",
	Roboticist: "battery-half",
	Scientist: "flask",
	"Security Officer": "shield-halved",
	"Shaft Miner": "digging",
	"Station Engineer": "gears",
	Warden: "handcuffs",
	Worker: "screwdriver-wrench",

	// Antag Icons

	Traitor: "jedi",
	"Blood Brother": "user-group",
	Spy: "user-secret",
	"Malf AI": "eye-slash",
	"Head Revolutionary": "hand-back-fist",
	Revolutionary: "hand-back-fist",
	Provocateur: "hand-back-fist",
	"Nuclear Operative": "users",
	"Clown Operative": "face-grin-tears",
	"Operative (Midround)": "users",
	"Lone Operative": "circle-radiation",
	"Contractor Support Unit": "x",
	"Operative Overwatch Agent": "jedi",
	"Syndicate Assault Cyborg": "jedi",
	"Syndicate Cyborg": "jedi",
	"Syndicate Infiltrator": "jedi",
	"Syndicate Medical Cyborg": "jedi",
	"Syndicate Monkey Agent": "jedi",
	"Syndicate Sabotage Cyborg": "jedi",
	"Battlecruiser Captain": "rocket",
	"Battlecruiser Crew": "rocket",
	Abductor: "shuttle-space",
	"Abductor Agent": "shuttle-space",
	"Abductor Scientist": "shuttle-space",
	"Abductor Solo": "shuttle-space",
	"Blob Infection": "virus-covid",
	Morph: "certificate",
	Heretic: "hamsa",
	"Heretic Smuggler": "hamsa",
	Changeling: "people-arrows",
	"Changeling (Midround)": "people-arrows",
	"Stowaway Changeling": "people-arrows",
	Cultist: "hands-holding-circle",
	Nightmare: "lightbulb",
	"Space Dragon": "dragon",
	"Space Ninja": "hurricane",
	Spider: "spider",
	Xenomorph: "locust",
	"Space Pirate": "skull-crossbones",
	Revenant: "ghost",
	"Paradox Clone": "shuffle",
	Fugitive: "person-running",
	"Fugitive Hunter": "person-running",
	"Pyroclastic Anomaly Slime": "water",
	Wizard: "hat-wizard",
	"Wizard (Midround)": "hat-wizard",
	Apprentice: "toolbox",
	"Slaughter Demon": "otter",

	// Other Icons

	Admin: "user-tie",
	Ghost: "ghost",
	Living: "heart",
	Unknown: "question",
	"Ancient Crew": "hands-holding-circle",
	"Ash Walker": "dragon",
	Hermit: "volcano",
	"Beach Bum": "beer-mug-empty",
	Lifebringer: "hand-holding-heart",
	"Space Bartender": "beer-mug-empty",
	"Cyber Police": "handcuffs",
	Glitch: "bug",
	"Lavaland Syndicate": "section",
	"Space Syndicate": "section",
	"Cybersun Space Syndicate": "section",
	"Cybersun Space Syndicate Captain": "section",
	"Derelict Drone": "robot",
	"Maintenance Drone": "robot",
	"Free Golem": "chess-rook",
	"Servant Golem": "chess-rook",
	"Venus Human Trap": "plant-wilt",
	"Ghost Role": "ghost",
	"Big Brother": "eye",
	"Bridge Assistant": "shield-heart",
	"Cargo Gorilla": "box",
	Cargorilla: "box",
	"Veteran Security Advisor": "person-cane",
	"Avatar of the Wish Granter": "wand-magic-sparkles",
	"revolution enemy": "hand-back-fist",
	"exiled headrev": "hand-back-fist",
	Santa: "sleigh",
	valentine: "heart",
	survivalist: "x",
	highlander: "face-angry",
	"ERT Generic": "x",
	Skeleton: "skull",
	"Unassigned Crewmember": "id-card",
	Blueshield: "shield",
	Synthetic: "handshake-angle",
	Virologist: "virus",
};

export const Joblist = {
	Station: {
		Command: [
			"Captain",
			"Head of Personnel",
			"Chief Engineer",
			"Quartermaster",
			"Chief Medical Officer",
			"Research Director",
			"Head of Security",
		],
		Security: [
			"Head of Security",
			"Warden",
			"Detective",
			"Brig Physician",
			"Security Officer",
		],
		Engineering: [
			"Chief Engineer",
			"Station Engineer",
			"Worker",
			"Atmospheric Technician",
		],
		Medical: [
			"Chief Medical Officer",
			"Medical Doctor",
			"Paramedic",
			"Chemist",
			"Coroner",
		],
		Science: ["Research Director", "Scientist", "Roboticist", "Geneticist"],
		Cargo: ["Quartermaster", "Cargo Technician", "Shaft Miner", "Bitrunner"],
		Service: [
			"Head of Personnel",
			"Nt Secretary",
			"Bartender",
			"Botanist",
			"Cook",
			"Janitor",
			"Clown",
			"Mime",
			"Curator",
			"Lawyer",
			"Chaplain",
			"Psychologist",
		],
		Silicon: ["AI", "Cyborg"],
		"No Department": ["Assistant", "Animal", "Prisoner"],
	},
	Antag: {
		Syndicate: [
			"Traitor",
			"Blood Brother",
			"Spy",
			"Malf AI",
			"Head Revolutionary",
			"Revolutionary",
			"Provocateur",
			"Nuclear Operative",
			"Clown Operative",
			"Operative (Midround)",
			"Lone Operative",
			"Contractor Support Unit",
			"Operative Overwatch Agent",
			"Syndicate Assault Cyborg",
			"Syndicate Cyborg",
			"Syndicate Infiltrator",
			"Syndicate Medical Cyborg",
			"Syndicate Monkey Agent",
			"Syndicate Sabotage Cyborg",
			"Battlecruiser Captain",
			"Battlecruiser Crew",
		],
		"Space Threat": [
			"Nightmare",
			"Space Dragon",
			"Space Ninja",
			"Spider",
			"Xenomorph",
			"Space Pirate",
			"Revenant",
			"Paradox Clone",
			"Fugitive",
			"Fugitive Hunter",
			"Pyroclastic Anomaly Slime",
		],
		Abductors: [
			"Abductor",
			"Abductor Agent",
			"Abductor Scientist",
			"Abductor Solo",
		],
		Biohazard: ["Blob Infection", "Morph"],
		Magic: [
			"Heretic",
			"Heretic Smuggler",
			"Changeling",
			"Changeling (Midround)",
			"Stowaway Changeling",
			"Cultist",
		],
		"Wizard Federation": [
			"Wizard",
			"Wizard (Midround)",
			"Apprentice",
			"Slaughter Demon",
		],
	},
	Other: {
		"Ghost Role": [
			"Ancient Crew",
			"Ash Walker",
			"Hermit",
			"Beach Bum",
			"Lifebringer",
			"Space Bartender",
			"Cyber Police",
			"Glitch",
			"Lavaland Syndicate",
			"Space Syndicate",
			"Cybersun Space Syndicate",
			"Cybersun Space Syndicate Captain",
			"Derelict Drone",
			"Maintenance Drone",
			"Free Golem",
			"Servant Golem",
			"Venus Human Trap",
			"Ghost Role",
		],
		Conditional: [
			"Big Brother",
			"Bridge Assistant",
			"Cargo Gorilla",
			"Cargorilla",
			"Veteran Security Advisor",
			"Avatar of the Wish Granter",
			"revolution enemy",
			"exiled headrev",
			"Santa",
			"valentine",
			"survivalist",
			"highlander",
		],
		"Non-Role": ["Admin", "Ghost", "Living", "Unknown"],
		Other: ["ERT Generic", "Skeleton", "Unassigned Crewmember"],
		Removed: ["Blueshield", "Synthetic", "Virologist"],
	},
};
