export const stationIcons: any = {
  AI: "eye",
  Animal: "paw",
  Assistant: "toolbox",
  "Atmospheric Technician": "fan",
  Bartender: "cocktail",
  Bitrunner: "gamepad",
  Botanist: "seedling",
  "Brig Physician": "shield-heart",
  Captain: "crown",
  "Cargo Technician": "box",
  Chaplain: "cross",
  Chemist: "prescription-bottle",
  "Chief Engineer": "user-astronaut",
  "Chief Medical Officer": "user-md",
  Clown: "face-grin-tears",
  Cook: "utensils",
  Coroner: "skull",
  Curator: "book",
  Cyborg: "robot",
  Detective: "user-secret",
  Geneticist: "dna",
  "Head of Personnel": "dog",
  "Head of Security": "user-shield",
  Janitor: "soap",
  Lawyer: "gavel",
  "Medical Doctor": "staff-snake",
  Mime: "comment-slash",
  "Nt Secretary": "clipboard-check",
  Paramedic: "truck-medical",
  Prisoner: "lock",
  Psychologist: "brain",
  Quartermaster: "sack-dollar",
  "Research Director": "user-graduate",
  Roboticist: "battery-half",
  Scientist: "flask",
  "Security Officer": "shield-halved",
  "Shaft Miner": "digging",
  "Station Engineer": "gears",
  Warden: "handcuffs",
  Worker: "screwdriver-wrench",
};
